import { Channel } from '../types';

export const MOCK_CHANNELS: Channel[] = [
  {
    id: '1',
    code: 'DIR',
    name: 'Direct',
    externalMappingId: undefined,
    description: 'Kênh đặt phòng trực tiếp',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'BKG',
    name: 'Booking.com',
    externalMappingId: 'BOOKING_API_12345',
    description: 'Kênh Booking.com',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'AGD',
    name: 'Agoda',
    externalMappingId: 'AGODA_API_67890',
    description: 'Kênh Agoda',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'EXP',
    name: 'Expedia',
    externalMappingId: 'EXPEDIA_API_11111',
    description: 'Kênh Expedia',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    code: 'TPC',
    name: 'Traveloka',
    externalMappingId: 'TRAVELOKA_API_22222',
    description: 'Kênh Traveloka',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    code: 'AIR',
    name: 'Airbnb',
    externalMappingId: 'AIRBNB_API_33333',
    description: 'Kênh Airbnb',
    isActive: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    code: 'GDS',
    name: 'GDS',
    externalMappingId: 'AMADEUS_GDS',
    description: 'Kênh Global Distribution System',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
