import { Currency } from '../types';

export const MOCK_CURRENCIES: Currency[] = [
  {
    id: '1',
    code: 'VND',
    name: 'Việt Nam Đồng',
    symbol: '₫',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'USD',
    name: 'US Dollar',
    symbol: '$',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    code: 'CNY',
    name: 'Chinese Yuan',
    symbol: '¥',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    code: 'KRW',
    name: 'Korean Won',
    symbol: '₩',
    isActive: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    code: 'GBP',
    name: 'British Pound',
    symbol: '£',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
