import { MarketSegment } from '../types';

export const MOCK_MARKET_SEGMENTS: MarketSegment[] = [
  {
    id: '1',
    code: 'COR',
    name: 'Corporate',
    description: 'Khách doanh nghiệp, công ty',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'FIT',
    name: 'FIT (Free Independent Traveler)',
    description: 'Khách du lịch tự do',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'GRP',
    name: 'Group',
    description: 'Đoàn khách, tour group',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'GOV',
    name: 'Government',
    description: 'Khách chính phủ, cơ quan nhà nước',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    code: 'WHL',
    name: 'Wholesale',
    description: 'Khách từ đại lý du lịch',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    code: 'AIR',
    name: 'Airline Crew',
    description: 'Đoàn bay, phi hành đoàn',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    code: 'WEB',
    name: 'Web Direct',
    description: 'Khách đặt trực tiếp qua website',
    isActive: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
