import { RoomType } from '../types';

export const MOCK_ROOM_TYPES: RoomType[] = [
  {
    id: '1',
    code: 'STD',
    name: 'Standard',
    description: 'Phòng tiêu chuẩn với đầy đủ tiện nghi cơ bản',
    sortOrder: 1,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'SUP',
    name: 'Superior',
    description: 'Phòng cao cấp hơn với view đẹp và diện tích rộng hơn',
    sortOrder: 2,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'DLX',
    name: 'Deluxe',
    description: 'Phòng sang trọng với nội thất cao cấp và tiện nghi đặc biệt',
    sortOrder: 3,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'STE',
    name: 'Suite',
    description: 'Phòng suite với phòng khách riêng biệt',
    sortOrder: 4,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    code: 'EXE',
    name: 'Executive',
    description: 'Phòng Executive dành cho khách doanh nhân với đặc quyền riêng',
    sortOrder: 5,
    isActive: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
