import { RoomCategory } from '../types';

export const MOCK_ROOM_CATEGORIES: RoomCategory[] = [
  {
    id: '1',
    code: 'STD-SGL',
    name: 'Standard Single',
    roomTypeId: '1', // Standard
    maxOccupancy: 1,
    bedType: 'Single',
    area: 20,
    basePrice: 800000,
    bedCount: 1,
    description: 'Phòng Standard 1 người',
    amenities: ['WiFi', 'TV', 'Điều hòa', 'Minibar'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'STD-DBL',
    name: 'Standard Double',
    roomTypeId: '1', // Standard
    maxOccupancy: 2,
    bedType: 'Double',
    area: 25,
    basePrice: 1000000,
    bedCount: 1,
    description: 'Phòng Standard 2 người giường đôi',
    amenities: ['WiFi', 'TV', 'Điều hòa', 'Minibar'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'STD-TWN',
    name: 'Standard Twin',
    roomTypeId: '1', // Standard
    maxOccupancy: 2,
    bedType: 'Twin',
    area: 25,
    basePrice: 1000000,
    bedCount: 2,
    description: 'Phòng Standard 2 người 2 giường đơn',
    amenities: ['WiFi', 'TV', 'Điều hòa', 'Minibar'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'SUP-DBL',
    name: 'Superior Double',
    roomTypeId: '2', // Superior
    maxOccupancy: 2,
    bedType: 'Double',
    area: 30,
    basePrice: 1500000,
    bedCount: 1,
    description: 'Phòng Superior giường đôi với view thành phố',
    amenities: ['WiFi', 'Smart TV', 'Điều hòa', 'Minibar', 'Bồn tắm'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    code: 'SUP-TWN',
    name: 'Superior Twin',
    roomTypeId: '2', // Superior
    maxOccupancy: 2,
    bedType: 'Twin',
    area: 30,
    basePrice: 1500000,
    bedCount: 2,
    description: 'Phòng Superior 2 giường đơn với view thành phố',
    amenities: ['WiFi', 'Smart TV', 'Điều hòa', 'Minibar', 'Bồn tắm'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    code: 'DLX-KNG',
    name: 'Deluxe King',
    roomTypeId: '3', // Deluxe
    maxOccupancy: 2,
    bedType: 'King',
    area: 40,
    basePrice: 2500000,
    bedCount: 1,
    description: 'Phòng Deluxe giường King với ban công riêng',
    amenities: ['WiFi', 'Smart TV 55"', 'Điều hòa', 'Minibar', 'Bồn tắm', 'Ban công', 'Nespresso'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    code: 'DLX-FAM',
    name: 'Deluxe Family',
    roomTypeId: '3', // Deluxe
    maxOccupancy: 4,
    bedType: 'King',
    area: 50,
    basePrice: 3500000,
    bedCount: 2,
    description: 'Phòng Deluxe gia đình với giường phụ',
    amenities: ['WiFi', 'Smart TV 55"', 'Điều hòa', 'Minibar', 'Bồn tắm', 'Ban công', 'Nespresso', 'Sofa bed'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    code: 'STE-JNR',
    name: 'Junior Suite',
    roomTypeId: '4', // Suite
    maxOccupancy: 2,
    bedType: 'King',
    area: 55,
    basePrice: 4000000,
    bedCount: 1,
    description: 'Junior Suite với khu vực tiếp khách',
    amenities: ['WiFi', 'Smart TV 65"', 'Điều hòa', 'Minibar', 'Jacuzzi', 'Ban công', 'Nespresso', 'Phòng khách'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    code: 'STE-STD',
    name: 'Suite',
    roomTypeId: '4', // Suite
    maxOccupancy: 3,
    bedType: 'King',
    area: 70,
    basePrice: 6000000,
    bedCount: 1,
    description: 'Suite đầy đủ với phòng khách và phòng làm việc riêng',
    amenities: ['WiFi', 'Smart TV 65"', 'Điều hòa', 'Minibar', 'Jacuzzi', 'Ban công', 'Nespresso', 'Phòng khách', 'Bàn làm việc'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    code: 'STE-PRS',
    name: 'Presidential Suite',
    roomTypeId: '4', // Suite
    maxOccupancy: 4,
    bedType: 'King',
    area: 120,
    basePrice: 15000000,
    bedCount: 2,
    description: 'Presidential Suite sang trọng nhất khách sạn',
    amenities: ['WiFi', 'Smart TV 75"', 'Điều hòa', 'Minibar', 'Jacuzzi', 'Ban công lớn', 'Nespresso', 'Phòng khách', 'Phòng ăn', 'Butler 24/7'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '11',
    code: 'EXE-KNG',
    name: 'Executive King',
    roomTypeId: '5', // Executive
    maxOccupancy: 2,
    bedType: 'King',
    area: 45,
    basePrice: 3000000,
    bedCount: 1,
    description: 'Phòng Executive với quyền vào Executive Lounge',
    amenities: ['WiFi', 'Smart TV 55"', 'Điều hòa', 'Minibar', 'Bồn tắm', 'Ban công', 'Nespresso', 'Executive Lounge'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '12',
    code: 'EXE-TWN',
    name: 'Executive Twin',
    roomTypeId: '5', // Executive
    maxOccupancy: 2,
    bedType: 'Twin',
    area: 45,
    basePrice: 3000000,
    bedCount: 2,
    description: 'Phòng Executive 2 giường với quyền vào Executive Lounge',
    amenities: ['WiFi', 'Smart TV 55"', 'Điều hòa', 'Minibar', 'Bồn tắm', 'Ban công', 'Nespresso', 'Executive Lounge'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
