import { RoomStatusDefinition } from '../types';

export const MOCK_ROOM_STATUS_DEFINITIONS: RoomStatusDefinition[] = [
  {
    id: '1',
    code: 'VACANT_CLEAN',
    name: 'Vacant Clean',
    description: 'Phòng trống và đã dọn dẹp sạch sẽ, sẵn sàng cho khách',
    category: 'Available',
    color: 'success',
    sortOrder: 1,
    isActive: true,
    isSystemDefault: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'VACANT_DIRTY',
    name: 'Vacant Dirty',
    description: 'Phòng trống nhưng chưa dọn dẹp',
    category: 'Available',
    color: 'warning',
    sortOrder: 2,
    isActive: true,
    isSystemDefault: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'OCCUPIED',
    name: 'Occupied',
    description: 'Phòng đang có khách lưu trú',
    category: 'Occupied',
    color: 'info',
    sortOrder: 3,
    isActive: true,
    isSystemDefault: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'CHECKIN',
    name: 'Check-in',
    description: 'Khách đang làm thủ tục nhận phòng',
    category: 'Transition',
    color: 'info',
    sortOrder: 4,
    isActive: true,
    isSystemDefault: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    code: 'CHECKOUT',
    name: 'Check-out',
    description: 'Khách đang làm thủ tục trả phòng',
    category: 'Transition',
    color: 'warning',
    sortOrder: 5,
    isActive: true,
    isSystemDefault: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    code: 'OOO',
    name: 'Out of Order',
    description: 'Phòng hỏng hóc, đang bảo trì',
    category: 'Maintenance',
    color: 'danger',
    sortOrder: 6,
    isActive: true,
    isSystemDefault: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    code: 'OOS',
    name: 'Out of Service',
    description: 'Phòng tạm ngưng phục vụ',
    category: 'Maintenance',
    color: 'secondary',
    sortOrder: 7,
    isActive: true,
    isSystemDefault: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    code: 'INSPECTED',
    name: 'Inspected',
    description: 'Phòng đã dọn và kiểm tra, sẵn sàng cho khách',
    category: 'Available',
    color: 'success',
    sortOrder: 8,
    isActive: true,
    isSystemDefault: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
