import { SourceCode } from '../types';

export const MOCK_SOURCE_CODES: SourceCode[] = [
  {
    id: '1',
    code: 'DIR',
    name: 'Direct',
    description: 'Khách đặt trực tiếp tại khách sạn',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'WEB',
    name: 'Website',
    description: 'Khách đặt qua website khách sạn',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'PHN',
    name: 'Phone',
    description: 'Khách đặt qua điện thoại',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'EML',
    name: 'Email',
    description: 'Khách đặt qua email',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    code: 'OTA',
    name: 'OTA',
    description: 'Khách đặt qua Online Travel Agency',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    code: 'AGN',
    name: 'Travel Agent',
    description: 'Khách đặt qua đại lý du lịch',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    code: 'REF',
    name: 'Referral',
    description: 'Khách được giới thiệu',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    code: 'REP',
    name: 'Repeat',
    description: 'Khách quay lại',
    isActive: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
